@startuml design

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
boundary CodeView
control CodePresenter

box "Client"
participant CodeView
participant CodePresenter
end box

box "Shared"
control EvalVisitor
end box

User -> CodePresenter : Runs a script
CodeView -> EvalVisitor : visit(tree)
EvalVisitor -> EvalVisitor : visit()
EvalVisitor -> CodeView : Outputs results

@enduml