@startuml design1
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor NonRegisteredUser
boundary LoginView
boundary SignupView
control SignupPresenter
control SignupServiceImpl
control SignupController
control SignupService
entity UserRepository
entity UserDTO
entity User
database Database 

box "NSheets Client"
participant LoginView
participant SignupView
participant SignupPresenter
end box

box "NSheets Shared"
participant UserDTO
end box

box "NSheets Server"
participant SignupServiceImpl
participant SignupController
participant SignupService
participant User
participant UserRepository
end box

box "Database"
participant Database
end box

NonRegisteredUser -> LoginView : onReveal() / navigate to page 
NonRegisteredUser -> LoginView : Select Signup request

LoginView -> SignupView : onReveal() / navigate to page 
SignupView -> NonRegisteredUser : Asks username, email, name, password and picture
NonRegisteredUser -> SignupPresenter : Inserts requested data
SignupPresenter -> NonRegisteredUser : Asks for confirmation
NonRegisteredUser -> SignupPresenter : Confirms

SignupPresenter -> UserDTO : dto : new UserDTO(email, name, username, password, pictureName, false)

SignupPresenter -> SignupServiceImpl : signupUser(dto)
SignupServiceImpl -> SignupController : signupUser(dto)
SignupController -> SignupService : signupUser(signupUser)
SignupService -> User : u : User.fromDTOHashPassword(dto)
SignupService -> UserRepository : save(u)
UserRepository -> Database : save

SignupServiceImpl -> SignupPresenter : onSuccess()
SignupPresenter -> SignupPresenter : redirect to login page
@enduml