@startuml Pedro
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User->Website: Selects the cell and enters the expression
Website->User: The system evaluates the expression and show it


@enduml