@startuml  analysis3

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
database Database order 100

User -> Browser : Edits an Agenda
Browser ->> Server : updateAgenda()
Server -> Database : updateAgenda()

Database -->> Server : return
Server -->> Browser : return
Browser -> User : display

@enduml