@startuml  analysis3

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
database Database order 100

User -> Browser : Edits an event
Browser ->> Server : updateCalendarEvent()
Server -> Database : update()

Server -->> Browser : return
Browser -> User : display

@enduml