@startuml  analysis2

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
database Database order 100

User -> Browser : Creates an event
Browser ->> Server : createCalendarEvent()
Server -> Database : save()

Server -->> Browser : return
Browser -> User : display

@enduml