@startuml  design4

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
boundary AgendaView
control AgendaPresenter
control AgendaServices
control DeleteAgendaController
control AgendaService
entity AgendaRepository
database Database 

box "Client"
participant AgendaView
participant AgendaPresenter 
end box

box "Server"
participant AgendaServices
participant DeleteAgendaController
participant AgendaService
participant AgendaRepository
end box

box "Database"
participant Database
end box

User -> AgendaPresenter : onReveal() / navigate to page 
AgendaPresenter ->> AgendaServices : deleteAgenda()
AgendaServices -> DeleteAgendaController : deleteAgenda()
DeleteAgendaController -> AgendaService : deleteAgenda()
AgendaService -> AgendaRepository : deleteAgenda()
AgendaRepository -> Database : fetch
AgendaServices ->> AgendaPresenter : return
AgendaPresenter -> AgendaView : return

@enduml