@startuml  design2

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
boundary CalendarView
control CalendarPresenter
control CalendarEventServices
control CreateCalendarEventController
control CalendarEventService
entity CalendarEventRepository
database Database 

box "Client"
participant CalendarView
participant CalendarPresenter 
end box

box "Server"
participant CalendarEventServices
participant CreateCalendarEventController
participant CalendarEventService
participant CalendarEventRepository
end box

box "Database"
participant Database
end box

User -> CalendarPresenter : onReveal() / navigate to page 
CalendarPresenter ->> CalendarEventServices : createCalendarEvent()
CalendarEventServices -> CreateCalendarEventController : createCalendarEvent()
CreateCalendarEventController -> CalendarEventService : addCalendarEvent()
CalendarEventService -> CalendarEventRepository : save()
CalendarEventRepository -> Database : fetch
CalendarEventServices ->> CalendarPresenter : onSuccess() 
CalendarPresenter -> CalendarView : setContents()

@enduml