@startuml  design1

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
boundary AgendaView
control AgendaPresenter
control AgendaServices
control ViewAgendasController
control AgendaService
entity AgendaRepository
database Database 

box "Client"
participant AgendaView
participant AgendaPresenter 
end box

box "Server"
participant AgendaServices
participant ViewAgendasController
participant AgendaService
participant AgendaRepository
end box

box "Database"
participant Database
end box

User -> AgendaPresenter : onReveal() / navigate to page 
AgendaPresenter ->> AgendaServices : getAgendas()
AgendaServices -> ViewAgendasController : viewAgendas()
ViewAgendasController -> AgendaService : getAllAgendas()
AgendaService -> AgendaRepository : findAllAgendas()
AgendaRepository -> Database : findAllAgendas()

AgendaServices ->> AgendaPresenter : return
AgendaPresenter -> AgendaView : return

AgendaView -> AgendaPresenter : getAllCalendarEventsToAgenda()
AgendaPresenter ->> AgendaServices : getAllCalendarEventsToAgenda()
AgendaServices -> ViewAgendasController : getAllCalendarEventsToAgenda()
ViewAgendasController -> AgendaService : getAllCalendarEventsToAgenda()
AgendaService -> AgendaRepository : getAllCalendarEventsToAgenda()
AgendaRepository -> Database : findAllAgendas()

AgendaServices ->> AgendaPresenter : return
AgendaPresenter -> AgendaView : return

@enduml