@startuml  design3

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
boundary CalendarView
control CalendarPresenter
control CalendarEventServices
control EditCalendarEventController
control CalendarEventService
entity CalendarEventRepository
database Database 

box "Client"
participant CalendarView
participant CalendarPresenter 
end box

box "Server"
participant CalendarEventServices
participant EditCalendarEventController
participant CalendarEventService
participant CalendarEventRepository
end box

box "Database"
participant Database
end box

User -> CalendarPresenter : onReveal() / navigate to page 
CalendarPresenter ->> CalendarEventServices : editCalendarEvent()
CalendarEventServices -> EditCalendarEventController : editCalendarEvent()
EditCalendarEventController -> CalendarEventService : updateCalendarEvent()
CalendarEventService -> CalendarEventRepository : 
CalendarEventRepository -> Database : fetch
CalendarEventServices ->> CalendarPresenter : onSuccess() 
CalendarPresenter -> CalendarView : setContents()

@enduml