@startuml  analysis4

skinparam monochrome true
skinparam shadowing false
hide footbox

actor User
database Database order 100

User -> Browser : Deletes an event
Browser ->> Server : deleteCalendarEvent()
Server -> Database : delete()

Server -->> Browser : return
Browser -> Browser : display

@enduml