@startuml  sd.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> MainMenu : asks for log in
create UserUI
MainMenu -> UserUI : create()
create UserController
MainMenu -> UserController : create()
MainMenu -> User : asks for credentials
User -> UserUI : inserts credentials
UserUI -> UserController : login() (...)
MainMenu -> User : login complete
User -> UserUI : chooses JavaScript Scription Option
UserUI -> User : asks for code
User -> UserUI : inserts code
UserUI -> nsheets.shared.core.js : visit()
nsheets.shared.core.js -> Settings : getWorkookSpreadSheet()
Settings -> Workbook : getWorkbook()
Workbook -> SpreadSheet : getSpreadSheet()
nsheets.shared.core.js -> nsheets.shared.core.js : processes code language and instructions
nsheets.shared.core.js -> Settings : changeWorkookSpreadSheet()
Settings -> Workbook : getWorkbook()
Workbook -> SpreadSheet : changeSpreadSheet()
nsheets.shared.core.js -> UserUI : returns the output
UserUI -> User : Shows the output to user
@enduml