@startuml us

skinparam monochrome true
skinparam shadowing false
hide footbox

User -> (US3: Add For Expressions)
User -> (US2: Add Assignment Expressions)
User -> (US1: Add Many Expressions )

@enduml