@startuml Pedro
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User->HomePresenter : Enter the name in the text box
HomePresenter->HomePresenter : getName()
HomePresenter -> WorkbookServicesAsync : searchWorkbook(name, callback)
WorkbookServicesAsync -> WorkbookServices: searchWorkbook(name)
WorkbookServices -> SearchWorkbooksController : searchedWorkbooksList : searchWorkbook(name)
SearchWorkbooksController->WorkbookRepositoty : workbooksList : findAll()
HomePresenter->HomePresenter : refreshViewAfterSearch(name) 
HomePresenter-->User : List the workbooks that contains the name introduced and notify with success
@enduml
