@startuml  analysis3.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> TextNotes : create

TextNotes -> TextNotes : organize by time stamp

@enduml