@startuml  dm.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

hide empty methods

class TextNote << (E,yellow) >> {
	String title
	String textNote
	Date date
}

@enduml