/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.isep.nsheets.server.lapr4.red.s2.ipc.n1160630.PDFStyleExport.domain;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import pt.isep.nsheets.shared.core.Spreadsheet;
import pt.isep.nsheets.shared.core.Workbook;

/**
 *
 * @author pedromonteiro
 */
public class PDFBuilder {
    
    private Workbook workbook;
    private static final Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
    private final String FILE_PATH = "../PDF.pdf";
    private final Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);

    public PDFBuilder(Workbook workbook) {
        this.workbook = workbook;
        File file = new File(FILE_PATH);
        file.getParentFile().mkdirs();
    }
    
    private void createTable(Section section) {

        int size = workbook.getSpreadsheetCount();


        for (int x = 0; x < size; x++) {
            Spreadsheet spreadsheet = workbook.getSpreadsheet(x);

            int row = spreadsheet.getRowCount();
            int col = spreadsheet.getColumnCount();

            PdfPTable table = new PdfPTable(col);
            PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);

            for (int y = 0; y < row; y++) {
                for (int k = 0; k < col; k++) {
                    table.addCell(spreadsheet.getCell(y, k).getContent());

                    if (y < col - 1) section.add(table);
                    if (k < row - 1) section.add(table);
                }
            }
        }

    }

    public boolean exportWorkbook() {
        
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE_PATH));
            document.open();
            fillMetaInfo(document);
            addTitlePage(document);
            addContent(document);
            document.close();
            return true;
        } catch (DocumentException | FileNotFoundException ex) {
            Logger.getLogger(PDFBuilder.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }

    private void fillMetaInfo(Document document) {
        document.addTitle("PDF exporter");
        document.addSubject("LAPR4");
        document.addKeywords("lapr4,2DB, pdf, export, algorithm, hardwork");
        document.addAuthor("LAPR4 2DB PDF GENERATOR");
        document.addCreator("LAPR4 2DB PDF GENERATOR");
    }

    private void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Export to PDF", catFont));
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Report generated by: Gonçalo Fonseca " + new Date()));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph("This document is your workbook in PDF Format ", smallBold));
        addEmptyLine(preface, 8);
        preface.add(new Paragraph("Workbook:" + workbook.name(), smallBold));
        addEmptyLine(preface, 9);
        preface.add(new Paragraph("Subject:" + workbook.description(), smallBold));
        document.add(preface);

    }

    private void addContent(Document document) {
        Chapter chapter = new Chapter(new Paragraph(" "), 0);
        Section section = chapter.addSection(new Paragraph(" "));
        document.newPage();
        createTable(section);
    }

    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
    
    public boolean createPdf() {
        try {
            
            Spreadsheet ss = workbook.getSpreadsheet(0);
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE_PATH));
            document.open();
            PdfPTable table;
            PdfPCell cell;
            Font font = FontFactory.getFont(FontFactory.HELVETICA, 12, Font.BOLD, BaseColor.WHITE);
            table = new PdfPTable(ss.getColumnCount());
            
            for(int firstLine = 0; firstLine <ss.getColumnCount();firstLine++ ){
                cell = new PdfPCell(new Phrase(ss.getCell(firstLine, 0).getContent(), font));
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                cell.setBorder(Rectangle.BOX);
                cell.setBorderColor(BaseColor.BLUE);
                cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }
            
//            for(int aw = 0; aw < ; aw++){
//                cell = new PdfPCell(new Phrase("hi", font));
//                cell.setBackgroundColor(BaseColor.WHITE);
//                cell.setBorder(Rectangle.BOX);
//                cell.setBorderColor(BaseColor.BLUE);
//                cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
//                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
//                table.addCell(cell);
//            }
            
            for(int i = 1; i<ss.getRowCount(); i++){
                for(int j = 0; j< ss.getColumnCount(); j++ ){
                cell = new PdfPCell(new Phrase(ss.getCell(i, j).getContent(), font));
                if(j == 0) {
                    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                }else{
                    cell.setBackgroundColor(BaseColor.WHITE);
                }
                cell.setBorder(Rectangle.BOX);
                cell.setBorderColor(BaseColor.BLUE);
                cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
                }
            }
            document.add(table);
            document.close();
            return true;
        } catch (IOException|  DocumentException ex) {
            Logger.getLogger(PDFBuilder.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        
    }
    
    
}
