@startuml  design1.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
boundary ExportView
control ExportPresenter
control ExportService
control ExportCSLController
control Settings
entity Workbook

box "NSheets Client"
participant ExportView
participant ExportPresenter
end box

box "Server"
participant Settings
participant Workbook
participant ExportService
entity WorkbookDTO
participant ExportCSLController
end box



User -> ExportPresenter : buttonClicked() / navigate to page
ExportPresenter ->> Settings : getWorkbook
ExportPresenter ->> Workbook : toDTO()
ExportPresenter ->> ExportService : exportWorkbookAsCLS(WorkbookDTO workbookDTO)
ExportService ->> WorkbookDTO : fromDTO();
ExportService -> ExportCSLController : exportWorkbook(Workbook workbook)

@enduml