@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> Browser : navigate to page 
Browser --> User : asks for the name
User -> Browser : inserts data 

Browser -> NSheetsApplication : addSideBar(name)

User -> Browser : switch side bar
Browser -> NSheetsApplication : switchActivatedSideBar(name)

Browser -> Browser : redirect extensions page

@enduml