@startuml  design2
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor AuthenticatedUser
boundary Js_complexLexer
boundary Js_complexParser
boundary ParseTree
boundary Code_JavascriptView
boundary Code_JavascriptPresenter
boundary EvalVisitor

box "NSheets Client"
participant Code_JavascriptView
participant Code_JavascriptPresenter 
end box

box "Antlr"
participant Js_complexLexer
participant Js_complexParser 
participant ParseTree 
participant EvalVisitor
end box

AuthenticatedUser -> Code_JavascriptPresenter : onReveal() / navigate to page 
Code_JavascriptPresenter -> Code_JavascriptView: shows view
Code_JavascriptView ->> AuthenticatedUser : shows the input box
AuthenticatedUser -> Code_JavascriptView : writes the code and clicks compile button
Code_JavascriptView -> Settings : getActiveSpeadCells();
Code_JavascriptView -> Js_complexLexer : new(code)
Code_JavascriptView -> Js_complexParser : new(lexer)
Code_JavascriptView -> ParseTree : parser.parse()
ParseTree -> EvalVisitor:
EvalVisitor -> EvalVisitor: reconizes a function 
EvalVisitor -> EvalVisitor: getFunctionContentFromList(function);
EvalVisitor -> Js_complexLexer : new(code)
EvalVisitor -> Js_complexParser : new(lexer)
EvalVisitor -> ParseTree : parser.parse()
Code_JavascriptView --> AuthenticatedUser: shows the result and the new function(s)

@enduml